# Generated by Django 4.0.5 on 2022-08-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_remove_film_files_remove_film_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='bid_file',
            new_name='bid_doc',
        ),
        migrations.AddField(
            model_name='film',
            name='bid_info',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
