# Generated by Django 4.0.5 on 2022-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_rename_bid_doc_film_bid_file_remove_film_bid_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='bid_file',
            new_name='bid_doc',
        ),
        migrations.AddField(
            model_name='film',
            name='bid_info',
            field=models.FileField(blank=True, upload_to='static'),
        ),
    ]
